version: "3.8"

services:
  user_server:
    build: ./
    depends_on:
      - user_db_mongo
    environment:
      - PRODUCTION=false
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules
    command: bash -c "npm install && npm run dev"
  user_db_mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=b86f941ff6362d48deae3f8243eae992
      - MONGO_INITDB_DATABASE=user_db
    volumes:
      - ./user_database_mongo:/data/db
